### ISSUE TITLE
[Feature Request] GitHub-Updater Support?

### ISSUE THREAD

**Issue by JanaME** [palasthotel/digitale-pracht#1]
![bildschirmfoto 2016-04-26 um 17 56 46](https://cloud.githubusercontent.com/assets/4892599/14824997/5f0d1e2c-0bd8-11e6-9789-625b84857ddd.png)

Feature Request for GitHub-Updater-Support, plz:

> ~@ImPalasthotel Solange https://github.com/palasthotel/digitale-pracht … noch nicht im http://w.org ->Repo steht, vllt https://github.com/afragen/github-updater … unterstützen?

**Comment by greatestview** [comment]
Just added
