### ISSUE TITLE
Grid 2.0 compatibility

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/digitale-pracht#11]
With Grid 2.0 the sidebar is dead. This leads to missing properties in grid-container.tpl.php like `firstcontentcontainer` could you please check this @greatestview ?

**Comment by EdwardBock** [comment]
https://github.com/palasthotel/digitale-pracht/blob/master/grid/grid-container.tpl.php#L38

https://github.com/palasthotel/digitale-pracht/blob/master/grid/grid-container.tpl.php#L99

**Comment by greatestview** [comment]
I’m going to look into this, when https://github.com/palasthotel/grid/issues/461 is fixed.

**Comment by greatestview** [comment]
Hey @EdwardBock, now I get a notice:

> NOTICE: UNDEFINED PROPERTY: PALASTHOTEL\GRID\STORAGE::$TEMPLATESPATH IN /…/WP-CONTENT/THEMES/DIGITALE-PRACHT/GRID/GRID-BOX-POSTS.TPL.PHP ON LINE 51

https://github.com/palasthotel/digitale-pracht/blob/master/grid/grid-box-posts.tpl.php#L51

`$this->storage->templatesPath` is not found. Is there a new way to access the templatesPath? Thank you!

**Comment by EdwardBock** [comment]
Yes there is. You can see how that works now in the default template: https://github.com/palasthotel/grid-wordpress/blob/master/public/core/templates/wordpress/grid-box-posts.tpl.php#L47

**Comment by greatestview** [comment]
A theme update has been submitted to WordPress, but not released so far. I’ll keep you updated.

**Comment by greatestview** [comment]
Version 1.27 has been released!

https://wordpress.org/themes/digitale-pracht/
https://github.com/palasthotel/digitale-pracht/releases/tag/v1.27

Beware it is not compatible with Gutenberg yet, so you need the Classic Editor plugin.
