### ISSUE TITLE
PHP Requirements

### ISSUE THREAD

**Issue by mkernel** [palasthotel/digitale-pracht#3]
@thomasbaumann came up with the following:

> Noch eine Kleinigkeit: PHP 5.3 kann sowas, was im Theme vorkommt, nicht:
> 
>  $min_width = digitalepracht_image_sizes()[ $image_format ][ 'width' ];
>  $min_height = digitalepracht_image_sizes()[ $image_format ][ 'height' ];
> 
> ...worüber ich auch schon häufiger gestolpert bin und wofür ich meine ganze VM
> gedistupgraded habe. Ich glaube, das geht ab 5.6. Vielleicht ein Hinweis für die
> Requirements.

in short: it seems the theme needs PHP 5.6 which we should note in the requirements. Should we?

**Comment by thomasbaumann** [comment]
or do something like

```
$size = digitalepracht_image_sizes();
$min_width = $size[ $image_format ][ 'width' ];
```

that should work with php 5.3

**Comment by greatestview** [comment]
Thanks! @thomasbaumann I just fixed that the way you suggested :)
