### ISSUE TITLE
Oembed movies are too large for smaller devices

### ISSUE THREAD

**Issue by chantalcoolsma** [palasthotel/digitale-pracht#4]
When you embed a movie into your post, it is shown too large on smaller devices. Apparently it misses some classes if you use the WordPress default way.

Any ideas how to solve this without changing the content?

**Comment by greatestview** [comment]
Hey @chantalcoolsma,

thanks for your report. Do you have an example for that? What kind of video are you embedding and where? YouTube videos should scale with the browser size in an aspect ratio of 16:9.

![bildschirmfoto 2016-10-05 um 12 58 11](https://cloud.githubusercontent.com/assets/2060276/19110644/68d73c06-8afb-11e6-995d-1175013b833d.png)

**Comment by chantalcoolsma** [comment]
Yes, see http://chantalcoolsma.nl/2016/08/29/muziek-terwijl-u-fietst/

I noticed the CSS, but no class is assigned in the source

**Comment by chantalcoolsma** [comment]
Something must go wrong here:

![schermafbeelding 2016-10-05 om 13 40 18](https://cloud.githubusercontent.com/assets/867632/19111717/5964eda8-8b01-11e6-88e5-efe3bba39b85.png)

**Comment by greatestview** [comment]
Hey @chantalcoolsma,

It seems like a plugin manipulates the video embed html code (left: your code, right: code without plugins):

![bildschirmfoto 2016-10-05 um 14 32 11](https://cloud.githubusercontent.com/assets/2060276/19113125/8e6aed02-8b08-11e6-9c95-1dbd2e900d5e.png)

Could you try turning on and off all plugins one after the other so that you can tell, which plugin is causing this?

**Comment by chantalcoolsma** [comment]
When I deactivate Jetpack, it works ok.

**Comment by chantalcoolsma** [comment]
Got it. It interferes with the "Shortcode-embeds" option of Jetpack. If you disable that one, it works ok.

https://jetpack.com/support/shortcode-embeds/

**Comment by greatestview** [comment]
Ah, interesting! Thank you. I‘ll check, if its possible for the theme to go around that.

**Comment by chantalcoolsma** [comment]
Besides that, is it still relevant for Jetpack to have that option? Oembed works for a lot of things, no need for shortcode embeds I think. Only for backwards compatibility.

**Comment by greatestview** [comment]
That was what I was thinking too, I don‘t think it is necessary anymore, since embedding videos by URL is a WordPress core by now. 👍

**Comment by greatestview** [comment]
Added CSS support for YouTube video embeds via _Jetpack Shortcode Embeds_ in version 1.11.
