### ISSUE TITLE
Strange Search Box 

### ISSUE THREAD

**Issue by benthebear** [palasthotel/digitale-pracht#6]
The Magnifyingglass of the Search box seems to be broken somehow …

![bildschirmfoto 2017-01-10 um 16 29 41](https://cloud.githubusercontent.com/assets/49137/21812087/17a58a10-d752-11e6-9f66-639c4522acab.png)

![bildschirmfoto 2017-01-10 um 16 30 28](https://cloud.githubusercontent.com/assets/49137/21812096/1ce931e8-d752-11e6-8cdc-6c82cb229e37.png)

**Comment by greatestview** [comment]
Fixed this visual bug inside the WordPress search widget with Version 1.13, [available now](http://digitale-pracht.de/digitale-pracht-ein-wordpress-theme-von-palasthotel/).
