### ISSUE TITLE
Readmore of Boxes

### ISSUE THREAD

**Issue by benthebear** [palasthotel/digitale-pracht#7]
You said, that you're not happy with the readmore-buttons of the Boxes, @greatestview …

![bildschirmfoto 2017-01-10 um 16 31 26](https://cloud.githubusercontent.com/assets/49137/21812165/41700bea-d752-11e6-8c99-a5d142401ea6.png)

**Comment by greatestview** [comment]
Added a new visual style for grid box read more links in Version 1.13, [available now](http://digitale-pracht.de/digitale-pracht-ein-wordpress-theme-von-palasthotel/).
